### SIGNUP
POST http://localhost:3000/auth/signup
Content-Type: application/json

{"username":"koba","email": "koba@hotmail.com", "password": "1234"}

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{"email": "bob@example.com", "password": "password456"}