### SIGNUP
POST http://localhost:3000/auth/signup
Content-Type: application/json

{"username":"gin","email": "tonic@hotmail.com", "password": "password123"}

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{"email": "tonic@hotmail.com", "password": "password123"}