### GET user information

GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc1NzA3MDMwMSwiZXhwIjoxNzU3MDczOTAxfQ.9O_OkGY2TM37ZspbyQgzimJdPXFkE7YD58ZWuxV01AM

### GET user conversation

GET http://localhost:3000/users/me/conversations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc1NzA3MDMwMSwiZXhwIjoxNzU3MDczOTAxfQ.9O_OkGY2TM37ZspbyQgzimJdPXFkE7YD58ZWuxV01AM
